name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: npm install
        working-directory: ./function-code
        env:
          CI: true
        run: |
          pwd
          npm ci --only=prod
      - name: npm install cdk modules
        env:
          CI: true
        run: |
          pwd
          npm ci
      - name: cdk synth
        id: synth
        run: npx cdk synth
      - name: cdk deploy
        id: cdk
        run: npx cdk deploy --require-approval never
